---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  fig.path = "man/figures/README-"
)
```
## Overview

<!-- badges: start -->
<!-- badges: end -->

**PWR**: Piecewise Regression (PWR) for time series (or structured longitudinal data) 
modeling and optimal segmentation by using optimized dynamic programming.

## Installation

You can install the PWR package from [GitHub](https://github.com/) with:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("fchamroukhi/PWR_R")
```

To build *vignettes* for examples of usage, type the command below instead:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("fchamroukhi/PWR_R", 
                         build_opts = c("--no-resave-data", "--no-manual"), 
                         build_vignettes = TRUE)
```

Use the following command to display vignettes:

```{r, eval = FALSE}
browseVignettes("PWR")
```

## Usage

```{r, message = FALSE}
library(PWR)

data("toydataset")

K <- 5 # Number of segments
p <- 3 # Polynomial degree

pwr <- fitPWRFisher(toydataset$x, toydataset$y, K, p)

pwr$plot()
```
