# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

costMatrix <- function(y, X, Lmin = 1) {
    .Call(`_PWR_costMatrix`, y, X, Lmin)
}

